//! LLM prompt module — type `#: <prompt>` + Enter and atty replaces
//! the typed line with a shell command generated by the LLM behind
//! `$LLM_API_BASE` (falls back to `$OLLAMA_HOST`).
//!
//! Default prefix is `#: ` — `#` is bash/zsh's comment character, so
//! if the module is disabled or the call fails, the original typed
//! text is at worst silently no-op'd by the shell rather than
//! executed. Configurable.
//!
//! Flow:
//!   1. User types `#: list all zig files` + Enter.
//!   2. onInput detects the prefix on the committed line, returns
//!      `Action.replace = "\x15"` — the proxy sends Ctrl+U to the
//!      shell which kills its readline buffer (the `#: …` text
//!      disappears from screen). The Enter is NOT forwarded.
//!   3. Worker thread (spawned at attach) POSTs to
//!      `${api_base}/v1/chat/completions` (OpenAI-compatible — works
//!      with Ollama via its /v1 endpoint, llama.cpp's server, vLLM,
//!      and OpenAI proper). Response JSON is parsed for
//!      `choices[0].message.content`.
//!   4. `pollShellInput` (called once per tick by the proxy) surfaces
//!      the response bytes; the proxy writes them to pty.master and
//!      readline echoes them as if the user had typed them. User
//!      reviews, edits, hits Enter to run.
//!
//! API endpoint resolution:
//!   - `$LLM_API_BASE` if set (e.g. `http://localhost:11434/v1`)
//!   - else `$OLLAMA_HOST` if set (Ollama's native env; we suffix `/v1`
//!     automatically — Ollama's native API isn't OpenAI-compatible
//!     but its `/v1/*` mirror is)
//!   - else: module is inert
//! Auth: `$LLM_API_KEY` becomes a `Bearer <key>` header if set.

const std = @import("std");
const m = @import("../module.zig");
const keymap = @import("../keymap.zig");
const Osc133 = @import("../osc133.zig").Osc133;
const pty_mod = @import("../pty.zig");
const Pty = pty_mod.Pty;
const parse = @import("llm/parse.zig");
const types = @import("llm/types.zig");
const dialog = @import("llm/dialog.zig");
const chat_persist = @import("llm/chat_persist.zig");
const sys_context = @import("llm/sys_context.zig");
const worker_mod_ns = @import("llm/worker.zig");
const env_mod_ns = @import("llm/env.zig");
const nowMs = @import("_lib.zig").nowMs;

extern "c" fn getenv(name: [*:0]const u8) ?[*:0]u8;

pub const Config = types.Config;
pub const ProviderEntry = types.ProviderEntry;
pub const Mode = types.Mode;
pub const ModeMask = types.ModeMask;
pub const Provider = types.Provider;
pub const HttpProvider = types.HttpProvider;
pub const SubprocessProvider = types.SubprocessProvider;

/// Convenience factories + preset constants for common provider
/// shapes. Users either grab a constant —
///
/// ```zig
/// .provider = atty.modules.llm.providers.claude_sonnet_4_6,
/// ```
///
/// — or build a tailored one via the factories:
///
/// ```zig
/// .provider = atty.modules.llm.providers.claudeCode(.{
///     .model = "claude-opus-4-7",
///     .extra_argv = &.{ "--permission-mode", "acceptEdits" },
/// }),
/// ```
pub const providers = struct {
    /// Build a subprocess provider for the Claude Code CLI's
    /// non-interactive mode (`claude -p --output-format json`).
    /// The CLI handles its own auth out of the user's `claude`
    /// login state; atty doesn't see or manage tokens. `model`
    /// empty → CLI default. `extra_argv` is appended after the
    /// `--model X` slot for `--permission-mode`, `--mcp-config`,
    /// etc.
    pub fn claudeCode(comptime options: struct {
        model: []const u8 = "",
        extra_argv: []const []const u8 = &.{},
    }) Provider {
        const argv = comptime blk: {
            const has_model = options.model.len > 0;
            const base_len: usize = if (has_model) 6 else 4;
            var buf: [base_len + options.extra_argv.len][]const u8 = undefined;
            buf[0] = "claude";
            buf[1] = "-p";
            buf[2] = "--output-format";
            buf[3] = "json";
            if (has_model) {
                buf[4] = "--model";
                buf[5] = options.model;
            }
            for (options.extra_argv, 0..) |a, i| buf[base_len + i] = a;
            const fixed = buf;
            break :blk &fixed;
        };
        return .{ .subprocess = .{
            .argv = argv,
            .prompt_via = .final_arg,
            .output = .{ .json_field = "result" },
            .timeout_ms = 60_000,
        } };
    }

    /// Variant of `claudeCode` that uses `--output-format
    /// stream-json` and parses the line-delimited events.
    /// Functionally equivalent today (the final command IS the
    /// `result` event's field) but lays the groundwork for paint-
    /// side partial-token streaming. `--verbose` and
    /// `--include-partial-messages` are added by atty — don't
    /// repeat them in `extra_argv` or claude will see duplicate
    /// flags (it tolerates this but it's noisy).
    pub fn claudeCodeStream(comptime options: struct {
        model: []const u8 = "",
        extra_argv: []const []const u8 = &.{},
        /// When true, atty captures the CLI's `session_id` from the
        /// first response's `type=system,subtype=init` event and
        /// passes it back as `--resume <id>` on subsequent dialog
        /// turns. Lets claude maintain its own conversation history
        /// — atty sends only the latest user turn each request
        /// rather than re-rendering the whole transcript. Off by
        /// default because it delegates conversation memory to the
        /// CLI; opt in deliberately.
        continuation: bool = false,
    }) Provider {
        const argv = comptime blk: {
            const has_model = options.model.len > 0;
            const base_len: usize = if (has_model) 8 else 6;
            var buf: [base_len + options.extra_argv.len][]const u8 = undefined;
            buf[0] = "claude";
            buf[1] = "-p";
            buf[2] = "--output-format";
            buf[3] = "stream-json";
            // `--verbose` is required for `--output-format
            // stream-json` per claude's CLI (otherwise the CLI
            // refuses with a usage error). `--include-partial-
            // messages` ensures we get the assistant deltas in
            // the stream for future paint-side wiring.
            buf[4] = "--verbose";
            buf[5] = "--include-partial-messages";
            if (has_model) {
                buf[6] = "--model";
                buf[7] = options.model;
            }
            for (options.extra_argv, 0..) |a, i| buf[base_len + i] = a;
            const fixed = buf;
            break :blk &fixed;
        };
        return .{ .subprocess = .{
            .argv = argv,
            .prompt_via = .final_arg,
            .output = .{ .json_stream = .{ .field = "result" } },
            .session = if (options.continuation) .{ .continuation = .{} } else .none,
            .timeout_ms = 60_000,
        } };
    }

    // ── Claude Code preset constants ─────────────────────────────
    //
    // Frozen Provider values for the current Claude family. New
    // model releases land as new constants — old ones stay so
    // users can pin a working config without chasing whatever
    // happens to be latest. Model IDs match Anthropic's published
    // identifiers as of the PR landing.

    /// Claude Sonnet 4.5 — fast, default for shell-command work.
    pub const claude_sonnet_4_5: Provider = claudeCode(.{ .model = "claude-sonnet-4-5" });
    /// Claude Sonnet 4.6 — the current Sonnet recommended for
    /// most agent flows.
    pub const claude_sonnet_4_6: Provider = claudeCode(.{ .model = "claude-sonnet-4-6" });
    /// Claude Opus 4.7 — biggest model. Slower + pricier but the
    /// best at hairy `#:` prompts (multi-step transformations,
    /// gnarly command pipelines).
    pub const claude_opus_4_7: Provider = claudeCode(.{ .model = "claude-opus-4-7" });
    /// Claude Haiku 4.5 — small + cheap. Good fit for the
    /// single-line `#: <intent>` flow when latency matters more
    /// than nuance.
    pub const claude_haiku_4_5: Provider = claudeCode(.{ .model = "claude-haiku-4-5-20251001" });
    /// CLI default — let `claude` pick whichever model the user
    /// last selected via `claude config`. Most "I don't care,
    /// just work" shape.
    pub const claude_default: Provider = claudeCode(.{});

    // ── HTTP preset constants ────────────────────────────────────

    /// Hosted OpenAI. Pair with `Config.model = "gpt-4o-mini"`
    /// (or any other OpenAI model id). Reads
    /// `$OPENAI_API_KEY` for auth.
    pub const openai: Provider = .{ .http = .{
        .api_base = "https://api.openai.com/v1",
        .api_key_env = "OPENAI_API_KEY",
    } };

    /// Local Ollama on the default port. Equivalent to the
    /// out-of-the-box HTTP defaults — included for symmetry so
    /// users can write `.provider = providers.ollama` without
    /// thinking about whether the defaults match.
    pub const ollama: Provider = .{ .http = .{
        .api_base = "http://localhost:11434/v1",
    } };

    // ── Other CLI presets ────────────────────────────────────────

    /// Simon Willison's `llm` CLI (https://llm.datasette.io).
    /// Pipes the prompt via stdin; expects raw stdout. Pass the
    /// model id and any extra argv (e.g. `&.{ "-s", "system…" }`).
    pub fn simonwLlm(comptime options: struct {
        model: []const u8,
        extra_argv: []const []const u8 = &.{},
    }) Provider {
        const argv = comptime blk: {
            var buf: [3 + options.extra_argv.len][]const u8 = undefined;
            buf[0] = "llm";
            buf[1] = "-m";
            buf[2] = options.model;
            for (options.extra_argv, 0..) |a, i| buf[3 + i] = a;
            const fixed = buf;
            break :blk &fixed;
        };
        return .{ .subprocess = .{
            .argv = argv,
            .prompt_via = .stdin,
            .output = .raw,
            .timeout_ms = 60_000,
        } };
    }
};

/// Submodule re-exports for tests + advanced users that want to
/// drive the HTTP worker or dialog envelope outside of `configure`.
/// Stable for internal use; not part of the public Suckless contract.
pub const dialog_ns = dialog;
pub const worker_ns = worker_mod_ns;

// `default_bindings` lives INSIDE the `configure()` return struct
// — see line ~115 below. The dispatcher's `@hasDecl(M, "default_bindings")`
// gate inspects the type that's actually stored in `config.modules`
// (which is `llm.configure(.{ ... })`, the inner struct), not the
// top-level `modules/llm.zig` file. A top-level decl here would be
// invisible to the walker and every Alt+letter binding would silently
// miss. Documenting this anti-pattern explicitly so it doesn't get
// re-introduced.

pub fn configure(comptime cfg: Config) type {
    // Comptime-validate config invariants that paint code relies on.
    // `inline_chat_rows < 3` would underflow `panel_rows - 2` in
    // `paintInlineChat` (one row each for divider + input → at least
    // one scrollback row needs panel_rows >= 3). Surface the bug at
    // build time, not at first Alt+C press.
    comptime {
        if (cfg.inline_chat_rows < 3) {
            @compileError("Config.inline_chat_rows must be >= 3 (divider + at least one scrollback row + input row)");
        }
        // Validate `cfg.providers[]` entries. HTTP entries need a
        // non-empty model id (empty would land as `"model":""` in
        // the request body which routes to an unintended default
        // or errors at the endpoint). Subprocess entries need a
        // non-empty argv[0]. Catch both at build time.
        for (cfg.providers, 0..) |entry, i| {
            switch (entry.config) {
                .http => |h| if (h.model.len == 0) {
                    @compileError(std.fmt.comptimePrint("Config.providers[{d}].config.http.model is empty", .{i}));
                },
                .subprocess => |s| if (s.argv.len == 0 or s.argv[0].len == 0) {
                    @compileError(std.fmt.comptimePrint("Config.providers[{d}].config.subprocess.argv must have a non-empty argv[0]", .{i}));
                },
            }
            if (!entry.for_modes.single and !entry.for_modes.dialog and !entry.for_modes.auto and !entry.for_modes.chat) {
                @compileError(std.fmt.comptimePrint("Config.providers[{d}].for_modes has every flag false — entry would never be picked", .{i}));
            }
        }
        // Single-provider shorthand also needs validation —
        // otherwise `.provider = .{ .http = .{ .model = "" } }`
        // (or subprocess with empty argv) would silently route
        // to an unintended default at request time.
        switch (cfg.provider) {
            .http => |h| if (h.model.len == 0) {
                @compileError("Config.provider.http.model is empty — set a model id");
            },
            .subprocess => |s| if (s.argv.len == 0 or s.argv[0].len == 0) {
                @compileError("Config.provider.subprocess.argv must have a non-empty argv[0]");
            },
        }
    }
    return struct {
        pub const name = "llm";
        pub const config = cfg;

        /// Module-registered key bindings. The dispatcher's
        /// `all_default_bindings` comptime-collects every module's
        /// `default_bindings` slice into the global keymap.
        /// User-supplied `config.keymap.bindings` win over these via
        /// the proxy's first-match scan — so a user can rebind any
        /// of these without touching this file, and a user who
        /// doesn't enable the LLM module at all gets none of these
        /// bindings.
        ///
        /// **Dual encoding rationale**: every Alt+letter chord ships
        /// TWICE — once as the legacy `\x1b<letter>` (terminals
        /// without kitty kbd) and once as the kitty kbd CSI-u sibling
        /// `\x1b[<code>;<mod>u` (Ghostty, kitty, foot, WezTerm).
        /// Atty's keymap matching runs BEFORE the CSI-u → legacy
        /// translation in the stdin path, so a single-encoded
        /// binding silently misses on half the terminal ecosystem.
        /// Only the legacy form sets `.label` and `.description` —
        /// the CSI-u sibling leaves them blank so the Alt+H help
        /// renderer dedupes by action.
        pub const default_bindings: []const keymap.Binding = &.{
            .{ .bytes = keymap.key("Alt+a"), .action = .llm_exec_single, .label = "Alt+A", .description = "LLM: single-shot (one command, no dialog)" },
            .{ .bytes = "\x1b[97;3u", .action = .llm_exec_single },
            .{ .bytes = keymap.key("Alt+s"), .action = .llm_exec_dialog, .label = "Alt+S", .description = "LLM: dialog mode (multi-turn exec/observe loop)" },
            .{ .bytes = "\x1b[115;3u", .action = .llm_exec_dialog },
            .{ .bytes = keymap.key("Alt+S"), .action = .llm_exec_auto, .label = "Alt+Shift+S", .description = "LLM: auto-exec mode (dialog + auto-confirm)" },
            .{ .bytes = "\x1b[115;4u", .action = .llm_exec_auto },
            .{ .bytes = keymap.key("Alt+m"), .action = .llm_exec_cycle_model, .label = "Alt+M", .description = "cycle through LLM models in config.models" },
            .{ .bytes = "\x1b[109;3u", .action = .llm_exec_cycle_model },
            .{ .bytes = keymap.key("Alt+h"), .action = .llm_exec_toggle_help, .label = "Alt+H", .description = "help (LLM mode hint, or global cheat-sheet)" },
            .{ .bytes = "\x1b[104;3u", .action = .llm_exec_toggle_help },
            .{ .bytes = keymap.key("Alt+c"), .action = .llm_inline_chat_toggle, .label = "Alt+C", .description = "toggle inline chat panel (shell stays visible)" },
            .{ .bytes = "\x1b[99;3u", .action = .llm_inline_chat_toggle },
            .{ .bytes = keymap.key("Alt+C"), .action = .llm_chat_overlay_toggle, .label = "Alt+Shift+C", .description = "toggle full-screen chat overlay" },
            .{ .bytes = "\x1b[99;4u", .action = .llm_chat_overlay_toggle },
            .{ .bytes = keymap.key("Ctrl+Shift+X"), .action = .llm_exec_cancel, .label = "Ctrl+Shift+X", .description = "cancel any active LLM exec / dialog / auto" },
            // Inline-panel focus jump — works only while the panel is
            // open. Ctrl+Up parks the panel + moves focus to the
            // shell prompt above; Ctrl+Down brings focus back.
            //
            // SINGLE-encoded by design (unlike Alt+letter chords).
            // The kitty kbd disambiguate flag atty pushes (flag 1)
            // doesn't re-encode arrow keys — modified arrows stay
            // legacy `\x1b[1;5A` / `\x1b[1;5B` on every terminal we
            // target. No CSI-u sibling needed.
            .{ .bytes = keymap.key("Ctrl+Up"), .action = .chat_focus_to_shell, .label = "Ctrl+Up", .description = "while inline chat is open: focus shell prompt (panel stays)" },
            .{ .bytes = keymap.key("Ctrl+Down"), .action = .chat_focus_to_chat, .label = "Ctrl+Down", .description = "while inline chat is open: focus chat input" },
            // Scrollback within a chat surface. PageUp/PageDown
            // aren't bound anywhere else in atty, so claiming them
            // unconditionally is safe — the action handler no-ops
            // when no chat surface is open AND the dispatcher hands
            // the keystroke back as `.forward`, so the shell still
            // sees PageUp normally.
            .{ .bytes = keymap.key("PageUp"), .action = .chat_scroll_page_up, .label = "PageUp", .description = "chat: scroll back one page (when chat surface is open)" },
            .{ .bytes = keymap.key("PageDown"), .action = .chat_scroll_page_down, .label = "PageDown", .description = "chat: scroll forward one page (when chat surface is open)" },
            // Jump-to-tail. Reverses PageUp scrolling without a
            // matching number of PageDowns. `Ctrl+End` instead of
            // bare `End` because the latter is already claimed by
            // `ghost_accept` in `defaults.zig` — atty's user-config
            // bindings beat module defaults in the match scan, so
            // a bare-End rebind here would be dead code. Modified
            // arrow forms (Ctrl+End, Ctrl+Home) aren't bound to
            // anything else in atty. Dual-encoded for kitty kbd +
            // legacy.
            .{ .bytes = keymap.key("Ctrl+End"), .action = .chat_scroll_to_tail, .label = "Ctrl+End", .description = "chat: jump back to the live tail (when scrolled up)" },
            .{ .bytes = "\x1b[1;5F", .action = .chat_scroll_to_tail },
            // Inline panel resize — grow/shrink the panel one row
            // per press. Dual encoded: `keymap.key("Ctrl+Alt+Up")`
            // resolves to the kitty kbd CSI-u form on terminals
            // that pushed flag 1; `\x1b[1;7A` is the legacy xterm
            // modifyOtherKeys encoding (modifier 7 = Ctrl+Alt;
            // Shift+Alt+Ctrl would be 8). Ctrl+Alt+Arrow is
            // rarely consumed by terminals so the binding lands
            // reliably.
            .{ .bytes = keymap.key("Ctrl+Alt+Up"), .action = .llm_chat_inline_grow, .label = "Ctrl+Alt+Up", .description = "inline chat: grow panel by one row" },
            .{ .bytes = "\x1b[1;7A", .action = .llm_chat_inline_grow },
            .{ .bytes = keymap.key("Ctrl+Alt+Down"), .action = .llm_chat_inline_shrink, .label = "Ctrl+Alt+Down", .description = "inline chat: shrink panel by one row" },
            .{ .bytes = "\x1b[1;7B", .action = .llm_chat_inline_shrink },
            // Chat-mode auto toggle. Dialog (confirm each exec) ↔
            // auto (atty auto-executes). Only meaningful inside a
            // chat surface; outside chat the persistent Alt+S /
            // Alt+Shift+S bindings own this distinction. Dual
            // encoded: kitty kbd CSI-u + legacy Alt+T.
            .{ .bytes = keymap.key("Alt+t"), .action = .llm_chat_toggle_auto, .label = "Alt+T", .description = "chat: toggle auto-exec" },
            .{ .bytes = "\x1b[116;3u", .action = .llm_chat_toggle_auto },
        };

        // HTTP worker thread + request/response plumbing extracted
        // to `llm/worker.zig`. The factory call binds `cfg` into
        // the worker module's types (Shared buffer sizes,
        // effective_system_prompt comptime resolution,
        // fixture_responses path, …). Each Aliased symbol below
        // keeps the existing call sites in this file using the
        // unqualified name; tests still hit the same surface via
        // the `pub` re-exports at the bottom.
        const worker_mod = worker_mod_ns.Module(cfg);
        pub const effective_system_prompt = worker_mod.effective_system_prompt;

        // Env-var resolution helpers live in `llm/env.zig` — same
        // factory pattern as worker.zig / dialog.zig. Aliased so
        // the `attach` site keeps using the unqualified names.
        const env_mod = env_mod_ns.Module(cfg);
        const resolveApiBase = env_mod.resolveApiBase;
        const resolveApiKey = env_mod.resolveApiKey;
        const resolveContextEnv = env_mod.resolveContextEnv;
        const resolveShell = env_mod.resolveShell;

        // Comptime-baked strings (inert-mode error notice + dialog
        // system prompt) live in `llm/consts.zig` so `llm/hooks.zig`
        // can read them without a circular import back into llm.zig.
        const llm_consts = @import("llm/consts.zig").Module(cfg);
        const inert_error_msg = llm_consts.inert_error_msg;
        const effective_dialog_system_prompt = llm_consts.effective_dialog_system_prompt;

        // RequestKind discriminator lives in worker.zig (single vs
        // dialog request body shape).
        const RequestKind = worker_mod.RequestKind;

        // Dialog-mode types live in `llm/dialog.zig` — pure enums +
        // a `Response(N)` factory. Re-exported here so existing
        // call sites keep using the unqualified names (`DialogState`,
        // `Turn`, …). The factory call resolves `cfg.max_response_bytes`
        // at comptime, giving back a Response struct sized correctly
        // for this configure() instance.
        const DialogState = dialog.State;
        const DialogAction = dialog.Action;
        const TurnKind = dialog.TurnKind;
        const Turn = dialog.Turn;
        const DialogResponse = dialog.Response(cfg.max_response_bytes);

        // Runtime-touching helpers from `llm/dialog.zig`. The factory
        // takes `Runtime` as a comptime arg because Runtime is
        // defined further down in this same `configure()` block; the
        // helpers are otherwise free of cfg-level dependencies. See
        // llm/dialog.zig's `Module()` for the body.
        const dialog_helpers = dialog.Module(cfg, Runtime);
        /// Wrapper around `dialog_helpers.pushTurn` that ALSO appends
        /// the new turn to the resolved `rt.chat_persist_path` (set
        /// by `attach` when `cfg.chat_persist_enabled`) so the chat
        /// history survives across atty sessions. Best-effort: disk
        /// failures are silent (the in-memory push has already
        /// succeeded by the time we attempt the append).
        ///
        /// Before appending, rotate the file if it has grown past
        /// `cfg.chat_persist_max_bytes` (when set). The rotation
        /// uses tmp+rename so a crash mid-rotation leaves the
        /// original intact.
        ///
        /// The loader in `attach` deliberately calls
        /// `dialog_helpers.pushTurn` DIRECTLY (not this wrapper) —
        /// otherwise it would re-append every loaded turn to the
        /// file on every startup, doubling content each run.
        fn pushTurn(rt: *Runtime, kind: dialog.TurnKind, content: []u8) !void {
            try dialog_helpers.pushTurn(rt, kind, content);
            if (rt.chat_persist_path.len > 0) {
                if (cfg.chat_persist_max_bytes > 0) {
                    _ = chat_persist.rotateIfExceeded(rt.allocator, rt.chat_persist_path, cfg.chat_persist_max_bytes);
                }
                _ = chat_persist.appendTurn(rt.allocator, rt.chat_persist_path, kind, content);
            }
        }
        const freeTurns = dialog_helpers.freeTurns;
        const appendCaptured = dialog_helpers.appendCaptured;
        const advancePastMarker = dialog_helpers.advancePastMarker;
        const captureConclusion = dialog_helpers.captureConclusion;
        const latchHint = dialog_helpers.latchHint;
        const latchErr = dialog_helpers.latchErr;
        const queueInjection = dialog_helpers.queueInjection;
        const dialogReset = dialog_helpers.dialogReset;
        const abortDialog = dialog_helpers.abortDialog;

        // Shared state struct (mutex + buffers shared between
        // proxy and worker thread) lives in `llm/worker.zig`.
        // Aliased so existing call sites keep using `Shared` and
        // `shared.req_buf` / `shared.res_done` / etc. unchanged.
        const Shared = worker_mod.Shared;

        pub const Runtime = struct {
            allocator: std.mem.Allocator,
            io: std.Io,
            shared: *Shared,
            /// Worker thread. `null` when the module is inert. For
            /// HTTP transport that means no `$LLM_API_BASE` /
            /// `$OLLAMA_HOST` set; for subprocess transport this is
            /// always non-null (CLI availability is a per-request
            /// concern, not an attach-time gate).
            thread: ?std.Thread,
            /// True when the module won't try to fire requests. Set
            /// once at attach and consulted by every key-binding /
            /// trigger site. Check this (not `api_base.len`) — the
            /// subprocess transport always has an empty `api_base`
            /// but is not inert.
            inert: bool = true,
            /// Live session id captured from the subprocess CLI's
            /// response stream (`cfg.provider.subprocess.session
            /// = .continuation`). Cleared on dialog reset
            /// (`Alt+Shift+R`). Owned by the runtime; freed in
            /// `detach`. Empty when no session is active or the
            /// transport doesn't support continuation.
            session_id: []u8 = &.{},
            /// Resolved at attach. Empty when transport is
            /// subprocess (CLI handles its own endpoint) or HTTP
            /// with no `$LLM_API_BASE` / `$OLLAMA_HOST` set.
            api_base: []u8 = &.{},
            /// Resolved at attach. Empty = no Authorization header
            /// (or transport is subprocess — CLI does its own auth).
            api_key: []u8 = &.{},
            /// Resolved shell name (basename of $SHELL or cfg.shell).
            shell: []u8 = &.{},
            /// Pre-built context line ("KEY=value, KEY2=value2") to
            /// append to the user message. Empty when no
            /// `context_env_vars` are configured or none of them
            /// are set in the environment. Owned by the runtime.
            context_blob: []u8 = &.{},
            /// Cached static system info (OS pretty-name + uname).
            /// Resolved ONCE at attach by `sys_context.gatherStatic`
            /// so we don't `read("/etc/os-release")` per request.
            /// Empty when `cfg.system_context.enabled` is false OR
            /// the underlying syscalls / file reads failed.
            /// Owned by the runtime; freed in detach.
            os_info: []u8 = &.{},
            /// Resolved chat-history file path — used by the
            /// pushTurn-wrapper to append every turn. Empty when
            /// persistence is disabled or path resolution failed
            /// (no HOME / XDG_DATA_HOME and no explicit override).
            /// Owned by the runtime; freed in detach.
            chat_persist_path: []u8 = &.{},
            /// Copy of the response surfaced via pollShellInput.
            /// Owned by the runtime; valid until the next poll.
            inject_buf: [cfg.max_response_bytes]u8 = undefined,
            inject_len: usize = 0,
            /// Latched explanation waiting to be surfaced via the
            /// next `provideHintText` call. One-shot: cleared on
            /// read so the hint row isn't re-painted forever.
            hint_buf: [512]u8 = undefined,
            hint_len: usize = 0,
            hint_pending: bool = false,
            /// Latched error-style notification waiting to be
            /// surfaced via the next `provideErrorText` call.
            /// Separate from `hint_buf` because the two slots have
            /// different styles + different precedence in the
            /// statusbar (errors win when both are active).
            err_buf: [512]u8 = undefined,
            err_len: usize = 0,
            err_pending: bool = false,
            /// Tracks whether we've already pushed the OSC 12
            /// cursor-colour change for the current prefix-typing
            /// session. Transition-driven (only emit on edge changes)
            /// so the terminal doesn't see redundant OSC traffic on
            /// every tick.
            cursor_signal_active: bool = false,
            /// True while a prompt is in flight.
            in_flight: bool = false,

            // ── AI mode state (the "explicit-actions" workflow) ──
            //
            // User types `#: ` (the prefix) → ai_mode_active flips
            // true → statusbar swaps to the AI hint → user presses
            // one of Alt+A / Alt+S / Alt+Shift+S to fire the
            // corresponding action. Enter in AI mode is swallowed
            // (no auto-fire). See `docs/llm-exec-mode-design.md`.
            ai_mode_active: bool = false,
            /// Set by `llm_exec_auto` (Alt+Shift+S). Causes the
            /// dialog handler's `.exec` arm to arm an auto-submit
            /// timer after injecting the suggested command, so the
            /// user doesn't have to press Enter for each step.
            /// Cleared by reset / cancel / `done`. Independent of
            /// `ai_mode_active`: auto-exec persists across the
            /// step-by-step dialog loop, while ai_mode_active
            /// tracks whether the user is currently TYPING a `#: …`
            /// prompt (false during the response/observation
            /// roundtrip).
            auto_mode_active: bool = false,
            /// Persistent dialog/auto MODE — stays on across multiple
            /// command cycles until the user explicitly deactivates
            /// (Esc / Ctrl+Shift+X / same-key toggle) OR the LLM
            /// emits `action=done`. While `.dialog` / `.auto`, every
            /// Enter on a non-empty line is treated as a
            /// conversational turn: the typed text is sent to the
            /// LLM as a `.user` turn AND the line still runs in the
            /// shell. This is distinct from `auto_mode_active`
            /// (which only controls the auto-submit timer for
            /// LLM-suggested commands) — they're set together when
            /// Alt+Shift+S toggles auto mode on, but `auto_mode_active`
            /// is the LOCAL flag the dialog state machine reads,
            /// while `dialog_persistent_mode` is the MACRO flag the
            /// proxy reads to decide "should this Enter become a
            /// conversational turn?".
            dialog_persistent_mode: enum { off, dialog, auto } = .off,
            /// True while waiting out the auto-submit countdown.
            /// Cleared by any user keystroke (the abort window),
            /// by the firing of the auto-submit itself, and by
            /// dialog reset / cancel / done.
            auto_exec_armed: bool = false,
            /// Monotonic ms timestamp when `auto_exec_armed` flipped
            /// to true. `onTick` fires the auto-submit when
            /// `nowMs() - auto_exec_t0_ms >= cfg.auto_delay_ms`.
            auto_exec_t0_ms: i64 = 0,
            /// Index into `cfg.providers[]` for the currently-
            /// selected provider entry. Wraps via `Alt+M`
            /// (`llm_exec_cycle_model`). Initialised to 0 at attach.
            /// Stays 0 forever when `cfg.providers` is empty; in
            /// that case `cfg.provider` (single-shorthand) is
            /// used and this index is irrelevant.
            current_provider_idx: usize = 0,
            /// Per-call format buffer for `statusText`. Used to
            /// inject the current provider label into the AI hint
            /// when `cfg.providers.len > 0` — `statusText` runs every
            /// render tick, but the returned slice only needs to
            /// outlive that single call, so a stable Runtime-owned
            /// buffer is the right shape.
            ///
            /// 1 KB to fit the styled variant: the AI-mode hint
            /// embeds ~7 SGR-wrapped shortcut tokens (~33 bytes
            /// each) + a styled icon (~26 bytes) + the model name
            /// + prose. ~300 bytes total before the model name;
            /// 1 KB leaves comfortable headroom for long model
            /// names like `claude-3-5-sonnet-20241022`. Longer
            /// hints are clipped by the statusbar's own width
            /// clamp anyway.
            status_buf: [1024]u8 = undefined,
            /// Pending bytes for pollShellInput to surface. Used to
            /// route `\x15` (Ctrl+U) to the pty after onAction
            /// triggers a worker call — `onAction` can't synchronously
            /// modify the stdin path, so it queues the kill-line byte
            /// here and the next pollShellInput tick drains it
            /// AHEAD of the response. The pending injection always
            /// fits in 16 bytes (a Ctrl+U or a short ESC sequence).
            pending_injection: [16]u8 = undefined,
            pending_injection_len: usize = 0,

            // ── Dialog mode state (Alt+S) ────────────────────────
            //
            // Distinct from the single-prompt path. State machine
            // walks `idle → generating → suggesting → executing →
            // capturing_output → observation_ready → generating` in
            // a loop until the LLM says `action=done` (or the user
            // cancels). See `DialogState` for the per-state
            // semantics. Single-mode requests leave `dialog_state`
            // untouched at `.idle`.
            dialog_state: DialogState = .idle,
            /// Conversation history. Heap-allocated turns, FIFO
            /// truncation at `cfg.history_turns_max`. Freed
            /// individually as they age out, and bulk-freed on
            /// cancel / detach.
            turns: [cfg.history_turns_max]Turn = undefined,
            turns_len: usize = 0,
            /// Captured output between OSC 133 `;C` and `;D` for
            /// the most recent exec step. Filled in `onOutput`;
            /// drained in `onTick` (built into the next observation
            /// turn) and reset to 0.
            /// Heap-promoted to keep Runtime's stack footprint small —
            /// at 16 KB default this dominated the inline-Runtime size.
            /// Allocated in `attach`, freed in `detach`.
            captured_output: *[cfg.captured_output_bytes]u8,
            captured_output_len: usize = 0,
            /// True when `captured_output` was filled to the cap
            /// and tail bytes were dropped. Surfaced in the
            /// observation turn with a "[truncated]" suffix so the
            /// model knows the output was clipped.
            captured_truncated: bool = false,
            /// Per-runtime OSC 133 tracker. The proxy has its own
            /// global tracker for subprocess push/pop; we maintain
            /// a SECOND independent one here so we own the `;C` /
            /// `;D` edge stream + offsets and can capture the exact
            /// byte ranges between markers. Parsing cost is
            /// negligible — character-state-machine, no
            /// allocation.
            osc133_capture: Osc133 = undefined,
            /// Pending command suggested by the LLM, displayed at
            /// the prompt while in `.suggesting`. The user reviews,
            /// optionally edits, and presses Enter (or cancels).
            /// Lives separately from `inject_buf` because the
            /// single-mode path uses that buffer with different
            /// lifetime semantics.
            pending_command: [cfg.max_response_bytes]u8 = undefined,
            pending_command_len: usize = 0,
            /// Description of the pending command (model's
            /// `description` field). Surfaced as the hint above
            /// the bar while in `.suggesting`. 256 bytes ≈ enough
            /// for a one-line summary; longer descriptions are
            /// truncated.
            pending_description: [256]u8 = undefined,
            pending_description_len: usize = 0,
            /// How many times we've already asked the LLM to re-do
            /// a malformed reply this dialog. Reset on dialog start
            /// and on a successful parse. Capped at
            /// `cfg.dialog_parse_retry_max` so an LLM that
            /// consistently refuses the JSON envelope can't trap
            /// the loop forever — after the cap, the dialog aborts
            /// with the same "wasn't valid JSON" error the user
            /// reported, but the user has at least had a chance
            /// for the model to self-correct.
            dialog_parse_retry_count: u8 = 0,
            /// Stored answer choices for the active question-mode
            /// turn. Populated by `handleDialogResponse` on
            /// `action=question` with `choices: [...]` JSON.
            /// Cleared on dialog reset and when the user submits
            /// their answer (free-text Enter OR ghost_pick). The
            /// `provideGhostList` hook reads from here to render
            /// the pick-list when state is
            /// `.awaiting_question_answer`.
            question_choices_storage: [dialog.max_choices][dialog.choice_max_len]u8 = undefined,
            question_choices_lens: [dialog.max_choices]usize = [_]usize{0} ** dialog.max_choices,
            question_choices_count: usize = 0,
            /// Scratch storage for the `[]const []const u8` slice
            /// `provideGhostList` returns. The slices point into
            /// `question_choices_storage`. Per-call rebuilt so
            /// callers see a stable snapshot for the duration of
            /// the hook.
            question_choices_slices: [dialog.max_choices][]const u8 = undefined,
            /// Captured conclusion text from the most recent
            /// `action=done`. Formatted as a multi-line block
            /// suitable for inline emission via the term-bytes
            /// hook (`provideTermBytes`). Persists across the
            /// dialog reset so `Alt+Shift+C` can re-emit it. Cleared
            /// only on `detach` and on a fresh `action=done`
            /// (which overwrites). Empty `conclusion_len == 0`
            /// means no completed dialog yet this session.
            conclusion_buf: [1024]u8 = undefined,
            conclusion_len: usize = 0,
            /// Latched flag — set by `handleDialogResponse` on
            /// `action=done` so the next `provideTermBytes` tick
            /// emits the conclusion banner (auto-show behaviour).
            /// Cleared after emission. The `Alt+Shift+C` action
            /// re-arms this flag for an explicit re-emit.
            conclusion_pending: bool = false,

            // ── Chat overlay (phase 2a — Alt+Shift+C) ───────────
            //
            // Persistent alt-screen overlay showing the LLM
            // conversation history. Alt+Shift+C toggles open/close
            // (Alt+C is the inline panel — see fields below). While
            // open, `onInput` swallows every keystroke so they don't
            // reach the shell. The OSC 1049 enter/exit pair is
            // emitted via `provideTermBytes`.
            chat_overlay_open: bool = false,
            /// Set whenever the overlay needs to paint (just
            /// opened, or just closed → need to emit the exit
            /// sequence). Cleared by `provideTermBytes` after the
            /// paint bytes have been returned.
            chat_overlay_paint_pending: bool = false,
            /// Rendered overlay bytes ready for `provideTermBytes`
            /// to return. Worst-case sizing under the structured
            /// renderer:
            ///   - exec turn:     ~800 B (256 desc + 480 cmd + SGR)
            ///   - done turn:     ~310 B (256 reason + SGR)
            ///   - question turn: ~3.0 KB (480 prompt + 9 × 256 choice + SGR)
            ///   - user/obs:      ~1.1 KB (1024 cap)
            /// The pathological case is all questions; cap that at
            /// ~3.5 KB/turn (including SGR + framing slack) and scale
            /// with `cfg.history_turns_max`. Extra 8 KB covers the
            /// alt-screen chrome (title bar, footer, input row,
            /// status hints). Overflow falls back to skip-the-paint,
            /// so it stays safe even past the worst case.
            chat_overlay_buf: [cfg.history_turns_max * 3584 + 8192]u8 = undefined,
            chat_overlay_buf_len: usize = 0,
            /// Chat input buffer — keystrokes accumulated while
            /// the overlay is open. Enter submits as a new
            /// `.user` turn and fires a dialog request; the
            /// response renders into the overlay's turn list.
            /// 1 KB is roughly 16 lines of typed prose at 60
            /// cols — plenty for follow-up clarifications.
            /// Longer inputs are rejected at the keystroke (the
            /// last char just gets dropped; no error).
            chat_input_buf: [1024]u8 = undefined,
            chat_input_len: usize = 0,
            /// Insertion cursor — invariant `<= chat_input_len`.
            /// Maintained by `applyChatEdit` in `llm/hooks.zig`;
            /// paint trusts the invariant and splits rendering
            /// around it (block-cursor glyph).
            chat_input_cursor: usize = 0,

            // ── Inline chat panel (Alt+C) ────────────────────────
            //
            // Alt+C — opens a slim chat panel ABOVE the statusbar
            // in the user's main screen (no alt-screen swap). The
            // shell stays visible above; the panel reserves N rows
            // at the bottom for a few lines of recent conversation
            // + a chat input row. Cursor focus moves to the input
            // row while open; statusbar.setReserveRows grows the
            // reservation, statusbar.applyReserveRows updates DECSTBM, and
            // the inline panel paints into the rows above the hint.
            // Closing restores the base reservation and returns the
            // cursor to the shell at the saved position.
            //
            // The full overlay (Alt+Shift+C) is still available and
            // mutually-exclusive — opening one closes the other.
            chat_inline_open: bool = false,
            /// Snapshot of `ctx.cursor_row` taken when the panel
            /// opens. The shell prompt row is load-bearing for paint:
            /// the real terminal cursor must end every paint here so
            /// echoed bytes land at the prompt, not inside the panel
            /// reservation. DECSC is unreliable upstream — proxy
            /// `applyReserveRows` runs its own DECSC/DECRC and
            /// overwrites the single slot. Explicit CUP via this
            /// snapshot survives. 0 sentinel = unknown (non-TTY,
            /// cursor_tracker unwired); the paint falls back to
            /// `shell_bottom`. Intentionally preserved through close
            /// so the close paint's CUP can still target it; the
            /// next open overwrites unconditionally.
            chat_open_cursor_row: u16 = 0,
            /// Companion to `chat_open_cursor_row` — the column where
            /// the prompt's input region ends (post-PS1). Without
            /// this, Ctrl+Up restores the cursor to column 1 and
            /// bash's next echoed keystroke lands at the start of
            /// the prompt row, not after the prompt characters.
            /// 0 sentinel = unknown; paint falls back to col 1.
            chat_open_cursor_col: u16 = 0,
            /// True when the user's keystroke focus is inside the
            /// inline chat panel (default whenever the panel opens).
            /// `Ctrl+Up` flips it to false → focus moves to the shell
            /// prompt above, panel stays painted but doesn't swallow
            /// keystrokes. `Ctrl+Down` flips it back.
            /// Meaningless when `chat_inline_open = false`.
            chat_focus_in_panel: bool = true,
            /// Latch armed by `handleDialogResponse`'s `.exec` arm
            /// when `cfg.inline_chat_autofocus_on_exec` AND the
            /// chat panel is open AND we're not in auto-mode.
            /// `onOutput`'s OSC 133 `;A`/`;D` edge handler clears
            /// it AND flips `chat_focus_in_panel` back to true, so
            /// the user lands back in the chat input after their
            /// command runs. `dialogReset` clears the latch on
            /// cancel paths so an aborted dialog doesn't ambush
            /// the user with a focus jump.
            chat_refocus_pending: bool = false,
            /// Flag the proxy reads via `extraReserveRows` — the
            /// proxy compares it to the live reserve baseline and
            /// emits `setReserveRows + activate` on the open/close
            /// transition so DECSTBM is updated before the first
            /// inline-panel paint.
            chat_inline_paint_pending: bool = false,
            /// Fast-path latch — set when only `chat_inline_input_buf`
            /// (the typed text) changed, so a full panel rewalk
            /// (per-turn `countTurnRows`, scrollback render) would
            /// be wasted work. `provideTermBytes` checks this AFTER
            /// the full `chat_inline_paint_pending` path and falls
            /// back to a full paint if the cached geometry doesn't
            /// match the current input shape (newline count grew /
            /// shrunk, cols changed, …). Only the keystroke handler
            /// sets it — every other state-change site continues to
            /// arm `chat_inline_paint_pending` for the full repaint.
            chat_inline_input_dirty: bool = false,
            /// Cached geometry from the last successful full
            /// `paintInlineChat`. The fast-path replays
            /// `paintInputBlock` against these coords without
            /// re-deriving them. Invalidated implicitly: any state
            /// change that warrants a full repaint sets
            /// `chat_inline_paint_pending`, which runs first and
            /// refreshes the cache.
            chat_inline_paint_cache_valid: bool = false,
            chat_inline_paint_input_top_row: u16 = 0,
            chat_inline_paint_input_row: u16 = 0,
            chat_inline_paint_input_newlines: u16 = 0,
            chat_inline_paint_total_cols: u16 = 0,
            /// Sized like the overlay's `chat_overlay_buf`. The
            /// inline panel is smaller (~8 rows × 200 cols) so 4 KB
            /// is plenty; matching the overlay's buffer keeps the
            /// rendering helpers fungible.
            chat_inline_buf: [4096]u8 = undefined,
            chat_inline_buf_len: usize = 0,
            /// Input buffer for inline chat — separate from
            /// `chat_input_buf` so the user can have an in-flight
            /// edit in the overlay AND in the inline panel without
            /// the two clobbering each other on toggle.
            chat_inline_input_buf: [1024]u8 = undefined,
            chat_inline_input_len: usize = 0,
            /// Insertion cursor offset within `chat_inline_input_buf` —
            /// same invariants as `chat_input_cursor` above.
            chat_inline_input_cursor: usize = 0,

            /// Turns scrolled back from the live tail in the overlay /
            /// inline panel respectively. 0 = pinned to latest; every
            /// `pushTurn` resets both so a new assistant reply always
            /// re-pins the view. PageUp/PageDown adjust the offset and
            /// the paint sites compute their visible window as
            /// `turns[..turns_len - offset]`. Clamped so the offset
            /// never exceeds `turns_len - 1` (one turn stays visible).
            chat_view_offset: usize = 0,
            chat_inline_view_offset: usize = 0,
            /// Live height override for the inline panel. `null` ⇒
            /// `cfg.inline_chat_rows`; Ctrl+Alt+Up bumps, Ctrl+Alt+Down
            /// trims, both clamped to `[3, ~]`. Resets to `null` on
            /// panel close so the next open starts at the configured
            /// default again.
            chat_inline_rows_override: ?u16 = null,
        };

        pub fn attach(allocator: std.mem.Allocator, io: std.Io) !Runtime {
            const shared = try allocator.create(Shared);
            shared.* = .{};
            errdefer allocator.destroy(shared);

            // Heap-promote the two biggest inline buffers off
            // Runtime so the stack footprint stays small even with
            // generous comptime config sizes (default totals: 16 KB
            // capture + 4 KB JSON).
            const captured_output = try allocator.create([cfg.captured_output_bytes]u8);
            errdefer allocator.destroy(captured_output);

            // Attach-time api_base / api_key resolution serves
            // two purposes only:
            //   1. The `should_spawn` inert-mode check below
            //      (skip the worker thread when the HTTP shorthand
            //      provider has no endpoint configured).
            //   2. The help-overlay endpoint display for the
            //      shorthand path (`hooks.zig:llm_exec_toggle_help`).
            // The worker NO LONGER reads these values directly —
            // each HTTP request resolves api_base/api_key per-
            // entry via `env.resolveHttpApiBase` / `resolveHttpApiKey`
            // so `cfg.providers[]` can hold multiple HTTP entries
            // with different env-var names.
            const api_base = try resolveApiBase(allocator);
            errdefer allocator.free(api_base);
            const api_key = try resolveApiKey(allocator);
            errdefer allocator.free(api_key);
            const shell_name = try resolveShell(allocator);
            errdefer allocator.free(shell_name);
            const context_blob = try resolveContextEnv(allocator);
            errdefer allocator.free(context_blob);
            // Static system context cached at attach — OS pretty-name +
            // kernel/arch. Resolved once so each LLM request doesn't
            // re-read /etc/os-release. Best-effort: failures land as
            // an empty slice, which `sys_context.compose` then skips.
            const os_info: []u8 = blk: {
                if (!cfg.system_context.enabled or !cfg.system_context.os) break :blk try allocator.dupe(u8, "");
                break :blk sys_context.gatherStatic(allocator) catch try allocator.dupe(u8, "");
            };
            errdefer allocator.free(os_info);

            // Spawn-or-skip decision. For HTTP transport, skip the
            // worker when no endpoint is configured — onInput /
            // pollShellInput already short-circuit on
            // `api_base.len == 0` so the inert state stays cheap.
            // For subprocess transport always spawn — CLI
            // availability is a runtime concern (subprocess spawn
            // errors surface as the next request's error_out), not
            // an attach-time gate.
            // Spawn the worker unless the module is statically
            // inert. Static-inert means: no providers[] AND the
            // single shorthand is an HTTP provider that resolved
            // to an empty api_base. Subprocess + any providers[]
            // entry means request-time dispatch will try at least
            // one path; we always spawn there.
            const should_spawn = cfg.providers.len > 0 or switch (cfg.provider) {
                .http => api_base.len > 0,
                .subprocess => true,
            };
            const thread: ?std.Thread = if (!should_spawn)
                null
            else
                try std.Thread.spawn(.{}, worker, .{ shared, io, allocator, shell_name, context_blob });

            var rt: Runtime = .{
                .allocator = allocator,
                .io = io,
                .shared = shared,
                .thread = thread,
                .inert = !should_spawn,
                .api_base = api_base,
                .api_key = api_key,
                .shell = shell_name,
                .context_blob = context_blob,
                .os_info = os_info,
                .osc133_capture = Osc133.init(allocator),
                .captured_output = captured_output,
            };

            // Chat-history persistence — when enabled, resolve the
            // path (default: ${XDG_DATA_HOME}/atty/chat.jsonl) and
            // load the last N turns from disk into the ring so the
            // chat panel + dialog context pick up where the previous
            // session left off. Best-effort: any I/O / path-resolve
            // failure leaves the ring empty AND disables further
            // persistence (chat_persist_path stays `&.{}`).
            if (cfg.chat_persist_enabled) {
                const resolved = chat_persist.resolvePath(allocator, cfg.chat_persist_path) catch &.{};
                if (resolved.len > 0) {
                    rt.chat_persist_path = resolved;
                    const max_bytes: usize = 4 * 1024 * 1024;
                    var loaded = chat_persist.loadLastTurns(allocator, resolved, cfg.history_turns_max, max_bytes) catch {
                        return rt;
                    };
                    defer loaded.deinit(allocator);
                    for (loaded.items) |t| {
                        // Direct dialog_helpers.pushTurn (not the
                        // wrapper) so loaded turns don't re-append
                        // to the file on every startup.
                        dialog_helpers.pushTurn(&rt, t.kind, t.content) catch {
                            allocator.free(t.content);
                        };
                    }
                }
            }

            return rt;
        }

        pub fn detach(rt: *Runtime, io: std.Io) void {
            // If the inline chat panel is open at shutdown, the
            // current paint left the real cursor hidden (`?25l`).
            // Without showing it again, the user's shell-after-exit
            // would have an invisible cursor until `tput cnorm` /
            // `reset`. Always-restore is safe: `?25h` is idempotent.
            if (rt.chat_inline_open) {
                _ = std.c.write(1, "\x1B[?25h", 6);
            }
            freeTurns(rt);
            rt.osc133_capture.deinit();
            // Heap-promoted Runtime buffers are owned by the main
            // thread alone — the worker reaches into `Shared`, not
            // these — so they can be freed even on the
            // worker-still-running path that intentionally leaks
            // worker-owned state below.
            rt.allocator.destroy(rt.captured_output);
            if (rt.chat_persist_path.len > 0) rt.allocator.free(rt.chat_persist_path);
            if (rt.thread) |t| {
                {
                    rt.shared.mutex.lockUncancelable(io);
                    defer rt.shared.mutex.unlock(io);
                    rt.shared.shutdown = true;
                    rt.shared.cv.signal(io);
                }
                // Detach instead of join. The worker may be blocked
                // inside a slow HTTP request (unreachable endpoint
                // / OS TCP timeout) and won't observe `shutdown`
                // until the request returns — joining would hang
                // atty's exit for tens of seconds. The OS reaps
                // the thread when the process exits; we deliberately
                // leak the heap allocations the worker still
                // references (shared / api_base / api_key / shell /
                // context_blob) because freeing them here is a
                // use-after-free race. detach() is the documented
                // escape hatch for exactly this "fire-and-forget at
                // process exit" case.
                t.detach();
                return;
            }
            // Inert mode (no worker spawned): safe to clean up
            // synchronously.
            if (rt.shared.res_buf) |old| rt.allocator.free(old);
            rt.allocator.destroy(rt.shared);
            rt.allocator.free(rt.api_base);
            rt.allocator.free(rt.api_key);
            rt.allocator.free(rt.shell);
            rt.allocator.free(rt.context_blob);
            rt.allocator.free(rt.os_info);
            if (rt.session_id.len > 0) rt.allocator.free(rt.session_id);
        }

        // ---- hooks --------------------------------------------------------

        // Hook entry points + dialog state-machine helpers live in
        // `llm/hooks.zig`. Same Module(cfg, Runtime) factory shape as
        // paint.zig / dialog.zig; re-exporting the pub hooks below
        // keeps the comptime dispatcher's @hasDecl walks working.
        const hooks = @import("llm/hooks.zig").Module(cfg, Runtime);
        pub const onInput = hooks.onInput;
        pub const onAction = hooks.onAction;
        pub const onOutput = hooks.onOutput;
        pub const onTick = hooks.onTick;
        pub const onLineCommit = hooks.onLineCommit;
        pub const pollShellInput = hooks.pollShellInput;

        /// One-shot hint surface: returns the latched explanation
        /// the first time it's called after a fresh response, then
        /// returns null until the next response arrives. Cleared
        /// on read so the hint row's TTL governs how long the
        /// text stays visible — the module doesn't keep
        /// re-painting.
        pub fn provideHintText(rt: *Runtime, ctx: *m.Context) m.Error!?[]const u8 {
            _ = ctx;
            if (!rt.hint_pending) return null;
            rt.hint_pending = false;
            return rt.hint_buf[0..rt.hint_len];
        }

        /// Multi-choice answer pick-list. Active when the LLM
        /// emitted `action=question` with a `choices: [...]` array
        /// — atty renders the choices via the same ghost_list path
        /// atuin uses, and `Ctrl+1..9` / `Esc+1..9` substitutes the
        /// picked choice text into the prompt. The user then
        /// presses Enter to submit (existing `awaiting_question_answer`
        /// path treats Enter as the answer turn).
        ///
        /// Returns null when:
        ///   - State isn't `.awaiting_question_answer`.
        ///   - Question was emitted without a `choices` array
        ///     (free-text answer expected).
        ///   - The user already started typing a free-text reply
        ///     (line non-empty) — the choices would shadow atuin's
        ///     history matches otherwise; we yield priority back.
        pub fn provideGhostList(rt: *Runtime, ctx: *m.Context) m.Error!?[]const []const u8 {
            if (rt.dialog_state != .awaiting_question_answer) return null;
            if (rt.question_choices_count == 0) return null;
            const line = ctx.line.current();
            if (line.len > 0) return null;
            for (0..rt.question_choices_count) |i| {
                rt.question_choices_slices[i] = rt.question_choices_storage[i][0..rt.question_choices_lens[i]];
            }
            return rt.question_choices_slices[0..rt.question_choices_count];
        }

        /// Sibling of `provideHintText` — surfaces a latched error
        /// notification (muted-red row above the status bar). Same
        /// one-shot semantics as `provideHintText`.
        pub fn provideErrorText(rt: *Runtime, ctx: *m.Context) m.Error!?[]const u8 {
            _ = ctx;
            if (!rt.err_pending) return null;
            rt.err_pending = false;
            return rt.err_buf[0..rt.err_len];
        }

        // Comptime SGR escape constants for the AI-mode statusbar
        // hint. The bar wraps the whole segment in `dim` (default
        // bar style); these inline escapes cancel dim around the
        // colored span and re-apply it after, so prose between
        // styled spans stays dim.
        //
        // Each open/close is a single combined CSI (`\x1B[a;b;cm`)
        // rather than three separate ones — saves ~6 bytes per
        // styled token, which matters because the statusbar's
        // line budget is finite and the hint embeds 7+ tokens.
        //
        // CSI 22 = normal intensity (cancels dim AND bold).
        // CSI 39 = default foreground.
        //
        // When the color is null, the corresponding wrap is empty
        // — segments inherit the bar's dim styling (legacy look).
        const icon_open: []const u8 = if (cfg.statusbar_icon_color) |c|
            std.fmt.comptimePrint("\x1B[22;38;5;{d}m", .{c})
        else
            "";
        const icon_close: []const u8 = if (cfg.statusbar_icon_color != null)
            "\x1B[39;2m"
        else
            "";
        const key_open: []const u8 = if (cfg.statusbar_shortcut_color) |c|
            std.fmt.comptimePrint("\x1B[22;1;38;5;{d}m", .{c})
        else
            "";
        const key_close: []const u8 = if (cfg.statusbar_shortcut_color != null)
            "\x1B[22;39;2m"
        else
            "";

        // Helper to wrap a shortcut token comptime so the assembled
        // hint string stays a const where possible.
        const Wrap = struct {
            fn key(comptime label: []const u8) []const u8 {
                return key_open ++ label ++ key_close;
            }
            fn icon(comptime glyph: []const u8) []const u8 {
                return icon_open ++ glyph ++ icon_close;
            }
        };

        // Pre-built status strings for the persistent dialog/auto
        // mode views. Comptime concatenation so the assembled
        // bytes are static — no per-tick formatting cost. The
        // shortcut tokens (Esc / Ctrl+Shift+X) are styled the same
        // as Alt+A / Alt+S in AI mode so visual vocabulary is
        // consistent across all status views.
        const ai_idle_hint = Wrap.icon("\u{2728}") ++ " AI \u{00B7} " ++
            Wrap.key("Alt+A") ++ " single \u{00B7} " ++
            Wrap.key("Alt+S") ++ " dialog \u{00B7} " ++
            Wrap.key("Alt+Shift+S") ++ " auto \u{00B7} " ++
            Wrap.key("Alt+M") ++ " model \u{00B7} " ++
            Wrap.key("Alt+H") ++ " help \u{00B7} " ++
            Wrap.key("Esc") ++ " cancel";
        const dialog_idle_hint = Wrap.icon("\u{1F916}") ++ " DIALOG mode \u{00B7} type prompt + Enter \u{00B7} " ++
            Wrap.key("Esc") ++ " / " ++ Wrap.key("Ctrl+Shift+X") ++ " to exit";
        const dialog_inflight_hint = Wrap.icon("\u{1F916}") ++ " DIALOG \u{00B7} " ++
            Wrap.icon("\u{1F9E0}") ++ " thinking\u{2026} \u{00B7} " ++
            Wrap.key("Esc") ++ " / " ++ Wrap.key("Ctrl+Shift+X") ++ " to exit";
        const auto_idle_hint = Wrap.icon("\u{26A1}") ++ " AUTO mode \u{00B7} type prompt + Enter \u{00B7} " ++
            Wrap.key("Esc") ++ " / " ++ Wrap.key("Ctrl+Shift+X") ++ " to exit";
        const auto_inflight_hint = Wrap.icon("\u{26A1}") ++ " AUTO \u{00B7} " ++
            Wrap.icon("\u{1F9E0}") ++ " thinking\u{2026} \u{00B7} " ++
            Wrap.key("Esc") ++ " / " ++ Wrap.key("Ctrl+Shift+X") ++ " to exit";
        const thinking_hint = Wrap.icon("\u{1F9E0}") ++ " thinking\u{2026}";

        // Compact discoverability hint shown when LLM is loaded but
        // not in AI mode (no `#: ` prefix typed, no dialog active).
        // The full AI hint (`ai_idle_hint`) only appears once the
        // user types `#: ` — so without this, a fresh shell shows
        // ZERO LLM-related hints and users don't discover Alt+C /
        // Alt+S / Alt+H. Keep it short — most of the statusbar
        // is "atty │ atuin" + this; verbose hints belong in Alt+H.
        const ai_discovery_hint = Wrap.icon("\u{2728}") ++ " " ++
            Wrap.key("Alt+C") ++ " chat \u{00B7} " ++
            Wrap.key("Alt+S") ++ " dialog \u{00B7} " ++
            Wrap.key("Alt+H") ++ " help";

        /// Statusbar hint while a chat surface is open. The panel
        /// header carries the structural shortcuts (`Alt+C close`,
        /// `Enter send`); the statusbar carries the mode/provider
        /// toggles where they're always visible without competing
        /// with the panel divider's column budget.
        const chat_open_hint = Wrap.icon("\u{2728}") ++ " " ++
            Wrap.key("Alt+T") ++ " auto \u{00B7} " ++
            Wrap.key("Alt+M") ++ " model";

        /// Reports whether the full chat overlay (Alt+Shift+C)
        /// currently owns atty's alt-screen on the user's outer
        /// terminal. The proxy queries this each master-read tick
        /// to decide whether to write shell output to stdout
        /// (overlay closed) or buffer it in the ring buffer for
        /// replay on close (overlay open). Distinct from
        /// `isInlineChatActive` (Alt+C) which doesn't claim the
        /// whole screen.
        pub fn isOverlayActive(rt: *Runtime) bool {
            return rt.chat_overlay_open;
        }

        /// Reports whether the inline chat panel (Alt+C) is currently
        /// claiming rows above the statusbar. Distinct from
        /// `isOverlayActive` because inline mode does NOT take over
        /// the screen — shell output keeps flowing in the rows above
        /// the panel, so the proxy must NOT divert master output into
        /// the overlay ring buffer. Used by the proxy to drive
        /// `sb.applyReserveRows` on toggle edges.
        pub fn isInlineChatActive(rt: *Runtime) bool {
            return rt.chat_inline_open;
        }

        /// Rows the inline chat panel wants reserved *above* the
        /// statusbar's base reservation. Returns 0 when the panel is
        /// closed; otherwise `cfg.inline_chat_rows + cfg.inline_chat_top_gap`
        /// (the top gap rows stay blank — visual breathing room
        /// between the shell prompt and the panel divider).
        pub fn extraReserveRows(rt: *Runtime) u16 {
            if (!rt.chat_inline_open) return 0;
            const rows = rt.chat_inline_rows_override orelse cfg.inline_chat_rows;
            return rows + cfg.inline_chat_top_gap;
        }

        /// SIGWINCH hook — dispatcher calls this after the statusbar
        /// has been re-activated at the new geometry. We arm the
        /// inline-panel paint latch (if the panel is open) so the
        /// next term-bytes tick re-renders chrome + input at the
        /// updated row/column positions. Cheap no-op when closed.
        pub fn onResize(rt: *Runtime) void {
            if (rt.chat_inline_open) {
                rt.chat_inline_paint_pending = true;
            }
        }

        pub fn statusText(rt: *Runtime, ctx: *m.Context) m.Error!?[]const u8 {
            // Chat surface open → swap the LLM discovery hint for
            // the chat-mode toggle hint (`Alt+T auto · Alt+M
            // model`). The panel header carries the structural
            // shortcuts (`Alt+C close · Enter send`); the statusbar
            // carries the mode/provider toggles so they're always
            // visible without competing for the panel's column
            // budget. `Alt+C` from the discovery hint would be
            // misleading anyway — it advertises "open the panel"
            // but the panel is already open. In-flight indicator
            // keeps precedence so users see "thinking…" while a
            // request is running.
            if (rt.chat_inline_open or rt.chat_overlay_open) {
                if (rt.in_flight) return thinking_hint;
                return chat_open_hint;
            }
            // Persistent dialog/auto mode segment takes precedence
            // over the transient "thinking…" indicator — the user
            // wants to know they're IN a mode persistently across
            // the entire interaction, more than they want
            // per-request "thinking" feedback. We still show the
            // thinking glyph as a suffix on the mode segment when
            // a request is in flight.
            //
            // Surface the mode hint when the dialog state machine
            // is engaged via either a persistent mode flag OR a
            // non-idle state. The state-engaged half closes the
            // visibility gap reported by the user: after LLM
            // `action=done` resets `dialog_persistent_mode` to .off,
            // the state machine can still be cycling toward the
            // next observation turn — without this gate the
            // statusbar fell back to the discovery hint and the
            // user thought the dialog was over.
            //
            // The single-shot (Alt+A) path keeps the `thinking_hint`
            // brain glyph: that flow only sets `in_flight = true`
            // without engaging the dialog state machine, so it
            // falls through the mode-engaged gate below into the
            // explicit `if (rt.in_flight)` branch.
            //
            // AUTO vs DIALOG selection prefers the persistent mode
            // flag — `mode == .dialog` always renders DIALOG even
            // if `auto_mode_active` is true (defends against the
            // single-mode-with-enter_action=.auto path that leaks
            // the flag without flipping persistent mode).
            const is_dialog_engaged = rt.dialog_persistent_mode != .off or
                rt.dialog_state != .idle;
            if (is_dialog_engaged) {
                const is_auto = switch (rt.dialog_persistent_mode) {
                    .auto => true,
                    .dialog => false,
                    .off => rt.auto_mode_active,
                };
                if (is_auto) {
                    return if (rt.in_flight) auto_inflight_hint else auto_idle_hint;
                }
                return if (rt.in_flight) dialog_inflight_hint else dialog_idle_hint;
            }

            // Single-shot Alt+A path: no persistent mode set and
            // `dialog_state` stays `.idle` (the single worker
            // request doesn't engage the multi-turn state machine).
            // Show the transient brain glyph so the user gets some
            // signal that work is in flight without claiming the
            // session is in DIALOG mode.
            if (rt.in_flight) return thinking_hint;

            // AI mode hint: when the line starts with the prefix,
            // surface the action keys so users discover the new
            // workflow. Takes precedence over the older single-
            // glyph `prefix_signal_status_text` indicator so the
            // hint string is what shows once the user has typed
            // `#: `.
            //
            // Esc and Ctrl+Shift+X both fire `llm_exec_cancel`.
            // Esc is the discoverable short form; Ctrl+Shift+X is
            // the safety lever for users on terminals that bind
            // Esc to something else, or who'd rather not have a
            // bare Esc grabbed inside AI mode.
            if (rt.ai_mode_active) {
                // With a `providers[]` list, surface the current
                // pick inline so `Alt+M` cycling has immediate
                // visible feedback in the statusbar. Single-
                // provider shorthand falls through to the static
                // hint — no name to interpolate.
                if (cfg.providers.len > 0) {
                    // Route through resolveProviderForMode so we
                    // surface the provider that WILL actually
                    // serve the next request — not just whatever
                    // sits at `current_provider_idx`. Without
                    // this, a `current_idx` pointing at a
                    // single-only entry while in chat mode would
                    // misadvertise.
                    const mode: types.Mode = mblk: {
                        if (rt.chat_inline_open or rt.chat_overlay_open) break :mblk .chat;
                        if (rt.auto_mode_active or rt.dialog_persistent_mode == .auto) break :mblk .auto;
                        if (rt.dialog_persistent_mode == .dialog or rt.dialog_state != .idle) break :mblk .dialog;
                        break :mblk .single;
                    };
                    const resolved = worker_mod_ns.resolveProviderForMode(
                        mode,
                        cfg.providers,
                        cfg.provider,
                        rt.current_provider_idx,
                    );
                    const pick: []const u8 = if (resolved.name.len > 0) resolved.name else switch (resolved.provider) {
                        .http => |h| if (h.model.len > 0) h.model else "(http)",
                        .subprocess => |s| if (s.argv.len > 0) s.argv[0] else "(subprocess)",
                    };
                    // Same shape as ai_idle_hint but with the
                    // current model name interpolated after `Alt+M`.
                    // Fallback drops to the static hint if the
                    // model name overruns status_buf.
                    return std.fmt.bufPrint(
                        &rt.status_buf,
                        "{s} AI \u{00B7} {s} single \u{00B7} {s} dialog \u{00B7} {s} auto \u{00B7} {s} {s} \u{00B7} {s} help \u{00B7} {s} cancel",
                        .{
                            Wrap.icon("\u{2728}"),
                            Wrap.key("Alt+A"),
                            Wrap.key("Alt+S"),
                            Wrap.key("Alt+Shift+S"),
                            Wrap.key("Alt+M"),
                            pick,
                            Wrap.key("Alt+H"),
                            Wrap.key("Esc"),
                        },
                    ) catch ai_idle_hint;
                }
                return ai_idle_hint;
            }

            // Legacy prefix signal — kept for users who set the
            // older `prefix_signal_status_text` to something custom
            // and don't want the verbose AI hint. Reachable only
            // when `ai_mode_active` is false (above branch took
            // precedence), which today is the same condition as
            // "prefix not matched" since the flag is wired to the
            // same check. Keeping the code path so a future change
            // (e.g. a config knob to suppress the verbose hint)
            // doesn't break custom users.
            if (cfg.prefix_signal_status) {
                const line = ctx.line.current();
                if (std.mem.startsWith(u8, line, cfg.prefix)) {
                    return cfg.prefix_signal_status_text;
                }
            }
            // Discoverability fallback: when nothing else is firing
            // (idle prompt, no AI mode, no in-flight request), surface
            // a compact hint so users see the LLM keys exist. Without
            // this, a fresh shell shows only "atty │ atuin" and the
            // Alt+C / Alt+S / Alt+H bindings are invisible until the
            // user types `#: ` (which they don't know to do until
            // they see the hint — chicken-and-egg). Opt out via
            // `cfg.show_idle_keys_hint = false`.
            if (cfg.show_idle_keys_hint) return ai_discovery_hint;
            return null;
        }

        // Paint surface — alt-screen chat overlay, inline chat
        // panel, OSC 12/112 cursor-colour transitions, and the
        // `provideTermBytes` hook that schedules them. Lifted into
        // `llm/paint.zig` so the configure() body stays scannable.
        const paint = @import("llm/paint.zig").Module(cfg, Runtime);
        pub const provideTermBytes = paint.provideTermBytes;

        // Dialog request body composition + parsed-response decoding
        // — re-exported from hooks.zig (which is where the in-module
        // call sites live). Tests reach these via L.parseDialogResponse
        // etc. through the configure() return.
        pub const buildDialogRequestBody = hooks.buildDialogRequestBody;
        pub const parseDialogResponse = hooks.parseDialogResponse;

        // ---- worker + HTTP RPC + extract helpers -------------------------
        //
        // Worker thread fn, doRequest, doDialogRequest, RequestResult,
        // writeStatic, buildRequestBody, extractCommand, extractResponse,
        // extractRawContent, ExtractedResponse all live in
        // `llm/worker.zig` now (factory-bound to `cfg`). Re-exports
        // below keep the existing `pub` surface on the configure()
        // factory stable so tests + downstream callers (the `attach`
        // site's `Thread.spawn(.{}, worker, …)` etc.) don't need
        // updating.
        pub const RequestResult = worker_mod.RequestResult;
        pub const ExtractedResponse = worker_mod.ExtractedResponse;
        pub const buildRequestBody = worker_mod.buildRequestBody;
        pub const extractCommand = worker_mod.extractCommand;
        pub const extractResponse = worker_mod.extractResponse;
        pub const extractRawContent = worker_mod.extractRawContent;
        const writeStatic = worker_mod.writeStatic;
        const doRequest = worker_mod.doRequest;
        const doDialogRequest = worker_mod.doDialogRequest;
        const worker = worker_mod.worker;

        // Pure response/sanitization helpers extracted to
        // `llm/parse.zig` — see there for security rationale and
        // tests.
        pub const decodeContent = parse.decodeContent;
        pub const sanitizeExplanation = parse.sanitizeExplanation;
        pub const stripControlBytes = parse.stripControlBytes;
        pub const sanitizeCommand = parse.sanitizeCommand;
    };
}

// ===========================================================================
// Tests — `llm_tests.zig` holds llm-core tests and cascades into
// `llm/paint_tests.zig` + `llm/hooks_tests.zig` for the sub-modules.
// ===========================================================================

test {
    _ = @import("llm_tests.zig");
}
