//! LLM prompt module — type `#: <prompt>` + Enter and atty replaces
//! the typed line with a shell command generated by the LLM behind
//! `$LLM_API_BASE` (falls back to `$OLLAMA_HOST`).
//!
//! Default prefix is `#: ` — `#` is bash/zsh's comment character, so
//! if the module is disabled or the call fails, the original typed
//! text is at worst silently no-op'd by the shell rather than
//! executed. Configurable.
//!
//! Flow:
//!   1. User types `#: list all zig files` + Enter.
//!   2. onInput detects the prefix on the committed line, returns
//!      `Action.replace = "\x15"` — the proxy sends Ctrl+U to the
//!      shell which kills its readline buffer (the `#: …` text
//!      disappears from screen). The Enter is NOT forwarded.
//!   3. Worker thread (spawned at attach) POSTs to
//!      `${api_base}/v1/chat/completions` (OpenAI-compatible — works
//!      with Ollama via its /v1 endpoint, llama.cpp's server, vLLM,
//!      and OpenAI proper). Response JSON is parsed for
//!      `choices[0].message.content`.
//!   4. `pollShellInput` (called once per tick by the proxy) surfaces
//!      the response bytes; the proxy writes them to pty.master and
//!      readline echoes them as if the user had typed them. User
//!      reviews, edits, hits Enter to run.
//!
//! API endpoint resolution:
//!   - `$LLM_API_BASE` if set (e.g. `http://localhost:11434/v1`)
//!   - else `$OLLAMA_HOST` if set (Ollama's native env; we suffix `/v1`
//!     automatically — Ollama's native API isn't OpenAI-compatible
//!     but its `/v1/*` mirror is)
//!   - else: module is inert
//! Auth: `$LLM_API_KEY` becomes a `Bearer <key>` header if set.

const std = @import("std");
const m = @import("../module.zig");
const lib = @import("_lib.zig");

extern "c" fn getenv(name: [*:0]const u8) ?[*:0]u8;

pub const Config = struct {
    /// Trigger prefix. When the committed line starts with this
    /// AND the user pressed Enter, the rest of the line becomes
    /// the prompt body. Default `#: ` — comment-safe in bash/zsh
    /// so a missed dispatch is a silent no-op, not an executed
    /// command.
    prefix: []const u8 = "#: ",
    /// LLM model identifier passed in the request body.
    model: []const u8 = "llama3:8b",
    /// Shell name for the user-prompt template. `null` → derive
    /// from `$SHELL` basename at attach time.
    shell: ?[]const u8 = null,
    /// Env-var name holding the API base URL. Read at attach.
    api_base_env: []const u8 = "LLM_API_BASE",
    /// Fallback env-var (typical Ollama setup). When this is read
    /// AND it doesn't already end in `/v1`, we append it.
    api_base_fallback_env: []const u8 = "OLLAMA_HOST",
    /// Env-var holding the API key. Optional — when unset we send
    /// no `Authorization` header (local servers usually accept
    /// unauthenticated requests).
    api_key_env: []const u8 = "LLM_API_KEY",
    /// System-role message. Aims at "one command, no explanation."
    /// Override to tune for your model's idiosyncrasies.
    system_prompt: []const u8 =
        "You are an expert shell user. Given a natural-language description, return EXACTLY ONE shell command that performs the task. Output ONLY the command on a single line. No markdown code fences. No explanation. No prefix or suffix text.",
    /// Per-request timeout in ms. Stored for future use; not yet wired
    /// to the HTTP client — requests may block indefinitely on a slow
    /// or unreachable endpoint until the OS TCP timeout fires.
    timeout_ms: u32 = 30_000,
    /// Maximum response size we'll store. The model may emit more;
    /// we truncate.
    max_response_bytes: comptime_int = 4096,
    /// Maximum prompt-body size (line.len - prefix.len). Larger
    /// inputs are ignored — likely paste / file content, not a
    /// natural-language task.
    max_prompt_bytes: comptime_int = 2048,
};

pub fn configure(comptime cfg: Config) type {
    return struct {
        pub const name = "llm";
        pub const config = cfg;

        const Shared = struct {
            mutex: std.Io.Mutex = .init,
            cv: std.Io.Condition = .init,
            /// Pending prompt set by onInput.
            req_buf: [cfg.max_prompt_bytes]u8 = undefined,
            req_len: usize = 0,
            req_pending: bool = false,
            /// Latest LLM response. `ready=true` and the proxy
            /// consumes it on the next pollShellInput.
            res_buf: [cfg.max_response_bytes]u8 = undefined,
            res_len: usize = 0,
            res_ready: bool = false,
            shutdown: bool = false,
        };

        pub const Runtime = struct {
            allocator: std.mem.Allocator,
            io: std.Io,
            shared: *Shared,
            thread: std.Thread,
            /// Resolved at attach. Empty = inert (no env var set).
            api_base: []u8 = &.{},
            /// Resolved at attach. Empty = no Authorization header.
            api_key: []u8 = &.{},
            /// Resolved shell name (basename of $SHELL or cfg.shell).
            shell: []u8 = &.{},
            /// Copy of the response surfaced via pollShellInput.
            /// Owned by the runtime; valid until the next poll.
            inject_buf: [cfg.max_response_bytes]u8 = undefined,
            inject_len: usize = 0,
            /// True while a prompt is in flight.
            in_flight: bool = false,
        };

        pub fn attach(allocator: std.mem.Allocator, io: std.Io) !Runtime {
            const shared = try allocator.create(Shared);
            shared.* = .{};
            errdefer allocator.destroy(shared);

            // Resolve env vars at attach time so the worker doesn't
            // have to re-read them per request.
            const api_base = try resolveApiBase(allocator);
            errdefer allocator.free(api_base);
            const api_key = try resolveEnv(allocator, cfg.api_key_env);
            errdefer allocator.free(api_key);
            const shell_name = try resolveShell(allocator);
            errdefer allocator.free(shell_name);

            const thread = try std.Thread.spawn(.{}, worker, .{ shared, io, allocator, api_base, api_key, shell_name });

            return .{
                .allocator = allocator,
                .io = io,
                .shared = shared,
                .thread = thread,
                .api_base = api_base,
                .api_key = api_key,
                .shell = shell_name,
            };
        }

        pub fn detach(rt: *Runtime, io: std.Io) void {
            {
                rt.shared.mutex.lockUncancelable(io);
                defer rt.shared.mutex.unlock(io);
                rt.shared.shutdown = true;
                rt.shared.cv.signal(io);
            }
            rt.thread.join();
            rt.allocator.destroy(rt.shared);
            rt.allocator.free(rt.api_base);
            rt.allocator.free(rt.api_key);
            rt.allocator.free(rt.shell);
        }

        // ---- env / config helpers ----------------------------------------

        fn resolveApiBase(allocator: std.mem.Allocator) ![]u8 {
            if (envValue(cfg.api_base_env)) |s| return allocator.dupe(u8, s);
            if (envValue(cfg.api_base_fallback_env)) |s| {
                if (std.mem.endsWith(u8, s, "/v1")) return allocator.dupe(u8, s);
                return std.fmt.allocPrint(allocator, "{s}/v1", .{s});
            }
            return allocator.dupe(u8, "");
        }

        fn resolveEnv(allocator: std.mem.Allocator, env_name: []const u8) ![]u8 {
            if (envValue(env_name)) |s| return allocator.dupe(u8, s);
            return allocator.dupe(u8, "");
        }

        fn resolveShell(allocator: std.mem.Allocator) ![]u8 {
            if (cfg.shell) |s| return allocator.dupe(u8, s);
            if (envValue("SHELL")) |s| {
                if (std.mem.lastIndexOfScalar(u8, s, '/')) |i| return allocator.dupe(u8, s[i + 1 ..]);
                return allocator.dupe(u8, s);
            }
            return allocator.dupe(u8, "sh");
        }

        fn envValue(env_name: []const u8) ?[]const u8 {
            // Null-terminated lookup via libc — we don't want to
            // walk std.os.environ ourselves.
            var name_buf: [128]u8 = undefined;
            if (env_name.len >= name_buf.len) return null;
            @memcpy(name_buf[0..env_name.len], env_name);
            name_buf[env_name.len] = 0;
            const v = getenv(@ptrCast(&name_buf)) orelse return null;
            const s = std.mem.sliceTo(v, 0);
            if (s.len == 0) return null;
            return s;
        }

        // ---- hooks --------------------------------------------------------

        pub fn onInput(rt: *Runtime, ctx: *m.Context, input: []const u8) m.Error!m.Action {
            const is_enter = blk: {
                for (input) |b| if (b == 0x0D or b == 0x0A) break :blk true;
                break :blk false;
            };
            if (!is_enter) return .forward;

            // Same lookup pattern as guardrail: applyInput already
            // ran, so the line we want is in lastCommitted.
            const line = ctx.line.lastCommitted() orelse ctx.line.current();
            if (!std.mem.startsWith(u8, line, cfg.prefix)) return .forward;

            const body = std.mem.trim(u8, line[cfg.prefix.len..], " \t");
            if (body.len == 0 or body.len > cfg.max_prompt_bytes) return .forward;
            if (rt.api_base.len == 0) return .forward; // inert without endpoint

            // Hand the prompt to the worker. Drop any in-flight
            // request (latest-wins) — pressing Enter twice
            // shouldn't queue two LLM calls.
            rt.shared.mutex.lockUncancelable(ctx.io);
            defer rt.shared.mutex.unlock(ctx.io);
            @memcpy(rt.shared.req_buf[0..body.len], body);
            rt.shared.req_len = body.len;
            rt.shared.req_pending = true;
            rt.shared.cv.signal(ctx.io);
            rt.in_flight = true;

            // `.replace = "\x15"` swaps the Enter for Ctrl+U
            // (unix-line-discard). readline kills the typed
            // `#: …` immediately — the user sees the line vanish
            // while we wait. The LLM response will be injected
            // via pollShellInput once it arrives.
            return .{ .replace = "\x15" };
        }

        pub fn pollShellInput(rt: *Runtime, ctx: *m.Context) m.Error!?[]const u8 {
            rt.shared.mutex.lockUncancelable(ctx.io);
            defer rt.shared.mutex.unlock(ctx.io);
            if (!rt.shared.res_ready) return null;
            const n = rt.shared.res_len;
            @memcpy(rt.inject_buf[0..n], rt.shared.res_buf[0..n]);
            rt.inject_len = n;
            rt.shared.res_ready = false;
            rt.shared.res_len = 0;
            rt.in_flight = false;
            return rt.inject_buf[0..rt.inject_len];
        }

        pub fn statusText(rt: *Runtime, ctx: *m.Context) m.Error!?[]const u8 {
            _ = ctx;
            if (rt.in_flight) return "\u{1F9E0} thinking…";
            return null;
        }

        // ---- worker -------------------------------------------------------

        fn worker(
            shared: *Shared,
            io: std.Io,
            gpa: std.mem.Allocator,
            api_base: []const u8,
            api_key: []const u8,
            shell_name: []const u8,
        ) void {
            var prompt_local: [cfg.max_prompt_bytes]u8 = undefined;
            var prompt_len: usize = 0;
            while (true) {
                shared.mutex.lockUncancelable(io);
                while (!shared.shutdown and !shared.req_pending) {
                    shared.cv.waitUncancelable(io, &shared.mutex);
                }
                if (shared.shutdown) {
                    shared.mutex.unlock(io);
                    return;
                }
                prompt_len = shared.req_len;
                @memcpy(prompt_local[0..prompt_len], shared.req_buf[0..prompt_len]);
                shared.req_pending = false;
                shared.mutex.unlock(io);

                // Fire the HTTP request OUTSIDE the lock — it may
                // block for many seconds.
                var response_buf: [cfg.max_response_bytes]u8 = undefined;
                const response_len = doRequest(
                    gpa,
                    io,
                    api_base,
                    api_key,
                    shell_name,
                    prompt_local[0..prompt_len],
                    &response_buf,
                ) catch 0;

                shared.mutex.lockUncancelable(io);
                if (response_len > 0) {
                    @memcpy(shared.res_buf[0..response_len], response_buf[0..response_len]);
                    shared.res_len = response_len;
                    shared.res_ready = true;
                }
                shared.mutex.unlock(io);
            }
        }

        /// One HTTP round-trip. Returns the trimmed command from
        /// `choices[0].message.content`, or 0 on any failure
        /// (network error, parse error, HTTP non-2xx, empty body).
        /// Failure mode is "user's typed line stays cleared, no
        /// new command injected" — visible as nothing happening.
        fn doRequest(
            gpa: std.mem.Allocator,
            io: std.Io,
            api_base: []const u8,
            api_key: []const u8,
            shell_name: []const u8,
            prompt: []const u8,
            out: []u8,
        ) !usize {
            const url = try std.fmt.allocPrint(gpa, "{s}/chat/completions", .{api_base});
            defer gpa.free(url);

            const body = try buildRequestBody(gpa, cfg.model, cfg.system_prompt, shell_name, prompt);
            defer gpa.free(body);

            var auth_buf: [256]u8 = undefined;
            const auth_header: ?[]const u8 = blk: {
                if (api_key.len == 0) break :blk null;
                if (api_key.len + 7 > auth_buf.len) break :blk null;
                break :blk std.fmt.bufPrint(&auth_buf, "Bearer {s}", .{api_key}) catch null;
            };

            var headers_buf: [2]std.http.Header = undefined;
            var headers_len: usize = 0;
            headers_buf[headers_len] = .{ .name = "Content-Type", .value = "application/json" };
            headers_len += 1;
            if (auth_header) |h| {
                headers_buf[headers_len] = .{ .name = "Authorization", .value = h };
                headers_len += 1;
            }

            var client: std.http.Client = .{ .allocator = gpa, .io = io };
            defer client.deinit(io);

            var response_storage: std.ArrayList(u8) = .empty;
            defer response_storage.deinit(gpa);
            var writer = response_storage.writer(gpa);

            const result = client.fetch(.{
                .location = .{ .url = url },
                .method = .POST,
                .payload = body,
                .extra_headers = headers_buf[0..headers_len],
                .response_writer = &writer,
            }) catch return 0;

            if (@intFromEnum(result.status) < 200 or @intFromEnum(result.status) >= 300) return 0;

            return extractCommand(response_storage.items, out);
        }

        // ---- pure helpers (testable) -------------------------------------

        /// Build the JSON request body. Pure — no I/O. Exposed for
        /// testing so we can assert exact shape without a server.
        pub fn buildRequestBody(
            allocator: std.mem.Allocator,
            model: []const u8,
            system_prompt: []const u8,
            shell_name: []const u8,
            prompt: []const u8,
        ) ![]u8 {
            var allocating: std.Io.Writer.Allocating = .init(allocator);
            errdefer allocating.deinit();
            const writer = &allocating.writer;

            try writer.writeAll("{\"model\":");
            try std.json.Stringify.encodeJsonString(model, .{}, writer);
            try writer.writeAll(",\"messages\":[{\"role\":\"system\",\"content\":");
            try std.json.Stringify.encodeJsonString(system_prompt, .{}, writer);
            try writer.writeAll("},{\"role\":\"user\",\"content\":");

            var user_buf: [cfg.max_prompt_bytes + 64]u8 = undefined;
            const user_msg = try std.fmt.bufPrint(
                &user_buf,
                "Generate a {s} command to: {s}",
                .{ shell_name, prompt },
            );
            try std.json.Stringify.encodeJsonString(user_msg, .{}, writer);
            try writer.writeAll("}],\"stream\":false}");
            return allocating.toOwnedSlice();
        }

        /// Extract the assistant's command text from an OpenAI-style
        /// chat-completion JSON response. Strips surrounding markdown
        /// fences + leading/trailing whitespace, takes the first
        /// non-empty line. Returns bytes written to `out`, or 0 on
        /// parse failure / empty result.
        pub fn extractCommand(body: []const u8, out: []u8) usize {
            // Minimal extraction: find `"content":"…"`. Robust JSON
            // parsing would be nicer but std.json's Scanner is
            // heavyweight; for the well-known OpenAI shape this is
            // good enough.
            const key = "\"content\":\"";
            const start = std.mem.indexOf(u8, body, key) orelse return 0;
            var i: usize = start + key.len;
            var cmd_buf: [cfg.max_response_bytes]u8 = undefined;
            var cmd_len: usize = 0;
            while (i < body.len) : (i += 1) {
                const c = body[i];
                if (c == '\\' and i + 1 < body.len) {
                    const e = body[i + 1];
                    const decoded: u8 = switch (e) {
                        '"' => '"',
                        '\\' => '\\',
                        '/' => '/',
                        'n' => '\n',
                        't' => '\t',
                        'r' => '\r',
                        // Uncommon escapes (\b, \f, \uXXXX, …): skip both
                        // the backslash and the escape code so neither
                        // appears as a literal character in the output.
                        // \u needs 4 more hex digits skipped — handled
                        // below after the switch.
                        else => {
                            i += 1; // skip the escape code char
                            if (e == 'u') i += 4; // skip 4 hex digits
                            continue;
                        },
                    };
                    if (cmd_len < cmd_buf.len) {
                        cmd_buf[cmd_len] = decoded;
                        cmd_len += 1;
                    }
                    i += 1;
                    continue;
                }
                if (c == '"') break;
                if (cmd_len < cmd_buf.len) {
                    cmd_buf[cmd_len] = c;
                    cmd_len += 1;
                }
            }
            return sanitizeCommand(cmd_buf[0..cmd_len], out);
        }

        /// Trim markdown fences (```bash … ```) + whitespace + take
        /// the first non-empty line. Some models stubbornly wrap.
        pub fn sanitizeCommand(raw: []const u8, out: []u8) usize {
            var s = std.mem.trim(u8, raw, " \t\r\n");
            // Strip a leading code fence if present.
            if (std.mem.startsWith(u8, s, "```")) {
                if (std.mem.indexOfScalar(u8, s, '\n')) |nl| {
                    s = s[nl + 1 ..];
                } else {
                    s = s[3..];
                }
            }
            // Strip a trailing code fence.
            if (std.mem.endsWith(u8, s, "```")) {
                s = s[0 .. s.len - 3];
            }
            s = std.mem.trim(u8, s, " \t\r\n");
            // First line only.
            if (std.mem.indexOfScalar(u8, s, '\n')) |nl| s = s[0..nl];
            s = std.mem.trim(u8, s, " \t\r");
            const n = @min(s.len, out.len);
            @memcpy(out[0..n], s[0..n]);
            return n;
        }
    };
}

// ===========================================================================
// Tests
// ===========================================================================

const testing = std.testing;

test "configure exposes the expected hooks" {
    const L = configure(.{});
    try testing.expect(@hasDecl(L, "onInput"));
    try testing.expect(@hasDecl(L, "pollShellInput"));
    try testing.expect(@hasDecl(L, "statusText"));
    try testing.expectEqualStrings("llm", L.name);
}

test "buildRequestBody produces well-formed OpenAI chat-completion JSON" {
    const L = configure(.{ .model = "test-model" });
    const body = try L.buildRequestBody(testing.allocator, "test-model", "be terse", "bash", "list zig files");
    defer testing.allocator.free(body);

    try testing.expect(std.mem.indexOf(u8, body, "\"model\":\"test-model\"") != null);
    try testing.expect(std.mem.indexOf(u8, body, "\"role\":\"system\"") != null);
    try testing.expect(std.mem.indexOf(u8, body, "\"role\":\"user\"") != null);
    try testing.expect(std.mem.indexOf(u8, body, "be terse") != null);
    try testing.expect(std.mem.indexOf(u8, body, "Generate a bash command to: list zig files") != null);
    try testing.expect(std.mem.indexOf(u8, body, "\"stream\":false") != null);
    // No raw newlines in the JSON — system prompt may have them
    // and they must be escaped to \n.
    for (body) |c| try testing.expect(c != '\n');
}

test "buildRequestBody escapes user content correctly (quotes + backslashes)" {
    const L = configure(.{});
    const body = try L.buildRequestBody(
        testing.allocator,
        "m",
        "sys",
        "bash",
        "echo \"hello\\world\"",
    );
    defer testing.allocator.free(body);
    try testing.expect(std.mem.indexOf(u8, body, "\\\"hello") != null);
    try testing.expect(std.mem.indexOf(u8, body, "\\\\world") != null);
}

test "extractCommand pulls choices[0].message.content out of a chat response" {
    const L = configure(.{});
    var out: [64]u8 = undefined;
    const sample =
        \\{"id":"x","choices":[{"index":0,"message":{"role":"assistant","content":"ls *.zig"}}]}
    ;
    const n = L.extractCommand(sample, &out);
    try testing.expectEqualStrings("ls *.zig", out[0..n]);
}

test "extractCommand strips ```bash code fences" {
    const L = configure(.{});
    var out: [128]u8 = undefined;
    const sample =
        "{\"choices\":[{\"message\":{\"content\":\"```bash\\nls -la\\n```\"}}]}";
    const n = L.extractCommand(sample, &out);
    try testing.expectEqualStrings("ls -la", out[0..n]);
}

test "extractCommand decodes the common JSON escapes" {
    const L = configure(.{});
    var out: [128]u8 = undefined;
    const sample = "{\"choices\":[{\"message\":{\"content\":\"echo \\\"hi\\\"\"}}]}";
    const n = L.extractCommand(sample, &out);
    try testing.expectEqualStrings("echo \"hi\"", out[0..n]);
}

test "extractCommand skips uncommon escapes (\\b, \\f) without leaking the escape code char" {
    const L = configure(.{});
    var out: [128]u8 = undefined;
    // `\b` (backspace) between two words: the output must be "ab", not "ab" with a literal 'b'.
    const sample = "{\"choices\":[{\"message\":{\"content\":\"a\\bb\"}}]}";
    const n = L.extractCommand(sample, &out);
    // After fix: `\b` is fully skipped → "ab". Before fix: literal 'b' leaks → "abb".
    try testing.expectEqualStrings("ab", out[0..n]);
}

test "extractCommand skips \\uXXXX unicode escapes cleanly" {
    const L = configure(.{});
    var out: [128]u8 = undefined;
    // `\u0020` is a space. We don't decode it but we must not leak "u0020".
    const sample = "{\"choices\":[{\"message\":{\"content\":\"ls\\u0020-la\"}}]}";
    const n = L.extractCommand(sample, &out);
    // After fix: \u0020 is fully skipped → "ls-la". Before fix: "lsu0020-la".
    try testing.expectEqualStrings("ls-la", out[0..n]);
}

test "extractCommand only takes the first non-empty line (multi-line replies)" {
    const L = configure(.{});
    var out: [128]u8 = undefined;
    // Model returned a one-liner + chatter. We want only the command.
    const sample = "{\"choices\":[{\"message\":{\"content\":\"ls -la\\n# this lists all files\"}}]}";
    const n = L.extractCommand(sample, &out);
    try testing.expectEqualStrings("ls -la", out[0..n]);
}

test "extractCommand returns 0 on missing content field" {
    const L = configure(.{});
    var out: [32]u8 = undefined;
    try testing.expectEqual(@as(usize, 0), L.extractCommand("{\"error\":\"bad\"}", &out));
}

test "sanitizeCommand handles fence + whitespace combinations" {
    const L = configure(.{});
    var out: [64]u8 = undefined;
    // "  ls -la  " → trim to "ls -la" = 6 bytes.
    try testing.expectEqual(@as(usize, 6), L.sanitizeCommand("  ls -la  ", &out));
    try testing.expectEqualStrings("ls -la", out[0..6]);

    // "```bash\nls -la\n```" → strip fences + trim.
    try testing.expectEqual(@as(usize, 6), L.sanitizeCommand("```bash\nls -la\n```", &out));
    try testing.expectEqualStrings("ls -la", out[0..6]);
}
