//! atty's shipped defaults.
//!
//! Every knob the user's `src/config.zig` can override has its
//! default value here. The resolver in `src/config_resolver.zig`
//! merges: each `pub const` the user declares wins; everything else
//! falls through to this file.
//!
//! Style guide: **every subsystem is a struct with per-field defaults**,
//! even if it has just one knob today. Adding a sibling knob upstream
//! becomes "new field in the struct" — user configs pick up the new
//! default automatically without needing to migrate from `xxx_yyy`
//! flat decls to a `xxx { .yyy }` grouped decl. The only exception is
//! `modules`, which is a heterogeneous tuple and can't be a struct
//! field. **Users do not edit this file**; edit `src/config.zig`.

const atty = @import("atty");

// ───── Modules ────────────────────────────────────────────────────────────
//
// The default tuple is dependency-free: history reads/writes your
// shell's own ~/.bash_history / ~/.zsh_history file — no `atuin`
// binary required, no daemon. Atty's `bin.atty.sh` prebuilt
// distribution runs out of the box.
//
// Want atuin? Override `modules` in your `src/config.zig` — see
// `src/config.def.zig` for the documented opt-in.

pub const modules = .{
    atty.modules.guardrail.configure(.{}),
    atty.modules.history.configure(.{}),
};

// ───── Proxy tunables ─────────────────────────────────────────────────────

pub const Proxy = struct {
    /// poll() timeout — drives onTick cadence. Lower = more responsive
    /// suggestion expiry; higher = lower idle CPU.
    tick_interval_ms: i32 = 100,
};
pub const proxy: Proxy = .{};

// ───── Ghost overlay ──────────────────────────────────────────────────────

pub const Ghost = struct {
    /// Overlay style. Matches fish + zsh-autosuggestions: dim only.
    style: atty.Style = atty.style.presets.muted,
};
pub const ghost: Ghost = .{};

// ───── Terminal protocol negotiation ──────────────────────────────────────

pub const Terminal = struct {
    /// Push the kitty keyboard protocol's `disambiguate` flag on
    /// startup (and pop on exit). When on, terminals that support it
    /// (Ghostty/kitty/foot/WezTerm/…) emit distinct CSI-u sequences
    /// for keys that would otherwise collide with control bytes:
    ///
    ///     Ctrl+Shift+I  →  \x1b[105;6u   (instead of \t)
    ///     Ctrl+Tab      →  \x1b[9;5u
    ///     Ctrl+9        →  \x1b[57;5u    (had no legacy encoding)
    ///
    /// atty intercepts CSI-u sequences in the stdin path: matched
    /// bindings fire, unmatched ones are dropped (never forwarded to
    /// the shell). Without that drop, the shell would see the raw
    /// CSI-u bytes as input — most shells don't speak the protocol
    /// and would echo them as mojibake. The unaffected legacy keys
    /// (Ctrl+D/Ctrl+C/arrows/etc.) pass through unchanged.
    enable_kitty_keyboard: bool = true,
};
pub const terminal: Terminal = .{};

// ───── Keymap ─────────────────────────────────────────────────────────────

pub const Keymap = struct {
    /// dwm-style bindings array. Right / End / Ctrl+F accept the
    /// ghost suggestion; Ctrl+Shift+I toggles incognito (resolved via
    /// `keymap.key()` to the kitty-keyboard CSI-u byte sequence —
    /// requires `Terminal.enable_kitty_keyboard = true`, default on).
    /// Alt+i is bound as a fallback so it still works on terminals
    /// that don't speak the protocol.
    bindings: []const atty.keymap.Binding = &.{
        .{ .bytes = atty.keymap.key("Right"), .action = .ghost_accept },
        .{ .bytes = atty.keymap.key("End"), .action = .ghost_accept },
        .{ .bytes = atty.keymap.key("Ctrl+F"), .action = .ghost_accept },
        .{ .bytes = atty.keymap.key("Ctrl+Shift+I"), .action = .incognito_toggle },
        .{ .bytes = atty.keymap.key("Alt+i"), .action = .incognito_toggle },
        .{ .bytes = atty.keymap.key("Ctrl+Shift+D"), .action = .delete_history_match },
    },
};
pub const keymap: Keymap = .{};

// ───── Bottom status bar ──────────────────────────────────────────────────

pub const StatusBar = struct {
    /// Reserve rows at the bottom of the terminal for the indicator
    /// (via DECSTBM). Off by default — costs `reserve_rows` of vertical
    /// screen real estate.
    enabled: bool = false,
    /// How many bottom rows to reserve. The last row holds the text;
    /// rows above are blank visual padding above the shell's content.
    reserve_rows: u16 = 2,
    /// Style for the bar's default segments (base text + module
    /// contributions). Per-segment overrides (like incognito_style)
    /// take precedence inside their own segment.
    style: atty.Style = atty.style.presets.muted,
    /// Base text shown when no module contributes anything. Empty
    /// means the bar stays blank until a module sets something.
    base_text: []const u8 = "",
    /// Style for the 🔒 incognito segment specifically. Defaults to
    /// muted red (dim + red) so it pops against the rest of the bar.
    incognito_style: atty.Style = .{ .dim = true, .fg = 1 },
};
pub const statusbar: StatusBar = .{};
