//! atty's shipped defaults.
//!
//! Every knob the user's `src/config.zig` can override has its
//! default value here. The resolver in `src/config_resolver.zig`
//! merges: each `pub const` the user declares wins; everything else
//! falls through to this file.
//!
//! Adding a new tunable upstream means adding it here and to the
//! resolver — user configs pick it up automatically, no merge
//! required. **Users do not edit this file**; edit `src/config.zig`.

const atty = @import("atty");

// ───── Modules ────────────────────────────────────────────────────────────
//
// The default tuple is dependency-free: history reads/writes your
// shell's own ~/.bash_history / ~/.zsh_history file — no `atuin`
// binary required, no daemon. Atty's `bin.atty.sh` prebuilt
// distribution runs out of the box.
//
// Want atuin? Override `modules` in your `src/config.zig` — see
// `src/config.def.zig` for the documented opt-in.

pub const modules = .{
    atty.modules.guardrail.configure(.{}),
    atty.modules.history.configure(.{}),
};

// ───── Proxy tunables ─────────────────────────────────────────────────────

/// poll() timeout — drives onTick cadence. Lower = more responsive
/// suggestion expiry; higher = lower idle CPU.
pub const tick_interval_ms: i32 = 100;

// ───── Visual style ───────────────────────────────────────────────────────

/// Ghost overlay style. Matches fish + zsh-autosuggestions: dim only.
pub const ghost_style: atty.Style = atty.style.presets.muted;

// ───── Key bindings ───────────────────────────────────────────────────────

/// Right-arrow, End, and Ctrl+F all accept the ghost suggestion —
/// covering the conventions of fish, zsh-autosuggestions, and Emacs.
pub const bindings: []const atty.keymap.Binding = &.{
    .{ .bytes = atty.keymap.key("Right"), .action = .ghost_accept },
    .{ .bytes = atty.keymap.key("End"), .action = .ghost_accept },
    .{ .bytes = atty.keymap.key("Ctrl+F"), .action = .ghost_accept },
};

// ───── Bottom status bar ──────────────────────────────────────────────────

/// Reserve rows at the bottom of the terminal for a status indicator
/// (via DECSTBM). Off by default — costs `statusbar_reserve_rows` of
/// vertical screen real estate. When enabled, modules can contribute
/// segments via the optional `statusText` hook (joined with ` │ `).
pub const statusbar_enabled: bool = false;

/// How many bottom rows to reserve. The last row holds the text;
/// rows above are blank visual padding from the shell's content.
pub const statusbar_reserve_rows: u16 = 2;

/// Visual style for the status bar text.
pub const statusbar_style: atty.Style = atty.style.presets.muted;

/// Base text shown when no module contributes anything. Empty means
/// the bar stays blank until a module sets something.
pub const statusbar_base_text: []const u8 = "";
